### PR TITLE
Bars

### PR DESCRIPTION
**Pull request by salacryl**
Hi, 
my colleagues wanted to have bars to show differences.

There must be a BASE_URL_GRAPHIC in settings where 0.png - (n=vote-options).png are hostet.
Those 10 PNGs must have a dimension of 1x25px. 

There you go.

Greetings,
Björn

### CODE REVIEW

**Comment by M-Mueller** [comment]
Can you please also add the PNGs?

**Comment by salacryl** [comment]
done

**Comment by M-Mueller** [comment]
I like this feature! However, I will change it a bit to make deployment easier.

**Comment by salacryl** [comment]
I hoped, you will.
I also hope, you'll find time to extend it for an active vote.

**Comment by M-Mueller** [comment]
I created a new pull request for this (#24). Changes to your version:
- the bars are an option now
- the results get sorted by the number of votes
- the image is served directly by the server, no more additional configuration
- there is only one colour since I think the additional colours didn't add much information

**Pull request closed without merging**
